spring:
  data:
    mongodb:
      uri: mongodb://root:rootroot@${MONGO_HOST}:27017/${PIPELINE_MONGO_DATABASE}?authSource=admin
#      host: 192.168.10.30
#      port: 27017
#      database: test-api
#      username: root
#      password: rootroot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:23306/${PIPELINE_MYSQL_DATABASE}?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  cloud:
    loadbalancer:
      ribbon:
        enable: false

  kafka:
    bootstrap-servers: ${KAFKA_HOST}:9092
    groupId: test

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false # 在controller层就打开EntityManager
#    properties:
#      hibernate:
#        #        format_sql: true
#        #        generate_statistics: true # 将hibernate的统计打开来看看到底是不是被缓存了
#        enable_lazy_load_no_trans: true # 在没有事务的情况下允许懒加载
#        cache:
#          use_second_level_cache: true
#          use_query_cache: true
#          region:
#            factory_class: jcache
exec:
  slurmToken: xxxx
wareHouse:
  type: gitee #gitee gitea githup
  orgNo: minebiome
  token: xxxxxx



server:
  #  servlet:
  #    context-path: /pipeline
  port: 8889
  tomcat:
    basedir: ./logs
    accesslog:
      enabled: true
      directory: ${spring.application.name}_access_log
      pattern: "%t [%I] %{X-Forwarded-For}i %l %u %r %s %b %D"

# 工作路径
workDir: /data/nextflowDir
k8sWorkDir: /data/k8sData
userId: 1000
groupId: 1000
userHome:
#scriptDir: D:\Git\py-java\nextflow-java-api\workDir

nfImage: wybioinfo/nextflow:23.11.0


k8s:
  vscode:
    nextflowdata-data-k8sData: k8sData
    nextflowdata-config-workspace: workspace
  rstudio:
    nextflowdata-data-k8sData: k8sData
    nextflowdata-workspace: workspace
  pvc:
    - nextflowdata


nextflow:
  exec: nf
  tower-token: cb5e8c0426c7097794b101f6cf981d46478dfd8f
  tower-endpoint: http://192.168.10.30:82/tower/api

#gitea 地址


# readme临时路径

fluxServerUrl:
dockerRegistryUrl: http://192.168.10.30:5000

#wareHouse:
#  type: gitea #gitee gitea githup
#  orgNo: sxxyds
#  token: xxxx

send:
  error: curl http://localhost:8889/kafka/signal/TASKID/error

authDebug: true

